name: Nightly Coraza Check
on:
  pull_request:
    paths:
      - ".github/workflows/nightly-coraza-check.yaml"
  schedule:
    - cron: "0 4 * * *"

env:
  GO_VERSION: '1.26'

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Get last commit of coraza
        id: coraza-latest-commit
        run: echo "value=$(gh api repos/corazawaf/coraza/commits/main -q .sha)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch last coraza version
        run: go get -u github.com/corazawaf/coraza/v3@${{ steps.coraza-latest-commit.outputs.value }} && go mod tidy

      - name: Run unit tests
        run: go run mage.go test

      - name: Build site
        run: go run mage.go build
