name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

env:
  GO_VERSION: '1.26'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install npm dependencies
        run: npm ci
      - name: Lint
        run: go run mage.go lint
      - name: Go tests
        run: go run mage.go test
      - name: Frontend tests
        run: npm test
      - name: Build
        run: go run mage.go build
