name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

env:
  GO_VERSION: '1.26'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install npm dependencies
        run: npm ci
      - name: Lint
        run: go run mage.go lint
      - name: Go tests
        run: go run mage.go test
      - name: Frontend tests
        run: npm test
      - name: Build
        run: go run mage.go build
